### ISSUE TITLE
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.

### ISSUE THREAD

**Issue by hmkim** [BD2KGenomics/toil-rnaseq#149]
[error.txt](https://github.com/BD2KGenomics/toil-rnaseq/files/2226818/error.txt)

Hello, 

I have an two account in cluster server.

With one account, toil-rnaseq works well. but with the other account toil-rnaseq didn't work.

Could you check my issue ? 

I uploaded error logfile for my issue in above.

I ran the toil-rnaseq on virtualenv enviroment using virtualenv (e.g pip, python2).

Thank you.

**Comment by jvivian** [comment]
Hi @hmkim ,

The error `docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.` stems from the account not having Docker privileges. You will need to add the user to the Docker group, otherwise all of the docker commands require `sudo`, which is not done by default.  [Link to issue](https://stackoverflow.com/questions/21871479/docker-cant-connect-to-docker-daemon)

Cheers,
John
